export const DEFAULT_CURRENT_ID_MANAGE_ACCOUNT = 1;
export const DEFAULT_PAGE_SIZE = 12;
export const DEFAULT_CURRENT_PAGE = 1;
export const AUTHORIZATION_HEADER = 'Authentication';
export const AUTHORIZATION_BEARER = 'Bearer';
export const AUTHORIZATION_BASIC = 'Basic';
export const FILL_OUT_THIS_FILED_MESSAGE = 'Please fill out this field';
export const FIXED_PRICE = 2;
export const DATE_FORMAT = 'dd/MM/yyyy';
