#!/usr/bin/env bash

# Check if we actually have commits to push
commits=$(git log @{u}..)
if [ -z "$commits" ]; then
  exit 0
fi

# ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

color_print() {
  local color="$1"
  local message="$2"
  printf "${color}${message}${NC}\n"
}

color_print "${YELLOW}==Pre-Push=="

hasChanges=$(git diff)

pop_stash_files() {
  if [ -n "$hasChanges" ]; then
    color_print "${YELLOW}==Applying git stashed changes=="
    git stash pop
  fi
}

if [ -n "$hasChanges" ]; then
  color_print "${YELLOW}==Stashing unstaged changes=="
  git stash push --keep-index
fi

if [ -d .fvm ]; then
  color_print "${YELLOW}==.fvm detected in folder=="
  export PATH=".fvm/flutter_sdk/bin:$PATH"
  export PATH=".fvm/flutter_sdk/bin/cache/dart-sdk/bin:$PATH"
else
  color_print "${YELLOW}==.fvm NOT detected in folder=="
fi

flutter --version
dart --version
flutter clean
flutter pub get
dart run color_gen:generate

if [ $? -ne 0 ]; then
  color_print "${RED}==Error in color generation=="
  pop_stash_files
  exit 1
fi

flutter gen-l10n

if [ $? -ne 0 ]; then
  color_print "${RED}==Error in locale generation=="
  pop_stash_files
  exit 1
fi

dart run build_runner build --delete-conflicting-outputs

if [ $? -ne 0 ]; then
  color_print "${RED}==Error in code generation=="
  pop_stash_files
  exit 1
fi

color_print "${YELLOW}==Running flutter format=="

dart format .

if [ $? -ne 0 ]; then
  color_print "${RED}==Error in format=="
  pop_stash_files
  exit 1
fi

color_print "${GREEN}==Format completed=="

color_print "${YELLOW}==Running dart fix=="

dart fix --apply

hasNewFileFormatted=$(git diff)

if [ -n "$hasNewFileFormatted" ]; then
  git add .
  git commit -m "FORMATTED BY PRE-PUSH"
  color_print "${RED}==NEW CHANGES DETECTED | PUSH AGAIN=="
  exit 1
fi

if [ $? -ne 0 ]; then
  color_print "${RED}==Error in fix=="
  pop_stash_files
  exit 1
fi

color_print "${GREEN}==Fix completed=="

color_print "${YELLOW}==Running flutter analyzer=="

flutter analyze

if [ $? -ne 0 ]; then
  color_print "${RED}==Error in analyzer=="
  pop_stash_files
  exit 1
fi

color_print "${GREEN}==Analyzer Completed=="

color_print "${YELLOW}==Running tests=="

flutter test

if [ $? -ne 0 ]; then
  color_print "${RED}==Error in tests=="
  pop_stash_files
  exit 1
fi

color_print "${GREEN}==Test Completed=="

color_print "${YELLOW}==Running build=="

flutter build apk --debug

if [ $? -ne 0 ]; then
  color_print "${RED}==Error in build=="
  pop_stash_files
  exit 1
fi

color_print "${GREEN}==Build Completed=="

git restore .
dart format .
dart fix --apply

pop_stash_files
