import AntDesignProvider from '@core/provider/AntDesignProvider';
import '@styles/globals.scss';
import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';
import Layout from '../components/layout/Layout';
const notosans = Noto_Sans_KR({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Study mentor',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={notosans.className}>
        <AntDesignProvider>
          <Layout>{children}</Layout>
        </AntDesignProvider>
      </body>
    </html>
  );
}
