import DynamicLayout from '@components/layout/DynamicLayout';
import AntdConfigProvider from '@core/provider/AntdConfigProvider';
import '@core/styles/global.scss';
import type { Metadata } from 'next';
import { Noto_Sans_KR } from 'next/font/google';

const notosans = Noto_Sans_KR({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Study mentor',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={notosans.className}>
        <AntdConfigProvider>
          <DynamicLayout>{children}</DynamicLayout>
        </AntdConfigProvider>
      </body>
    </html>
  );
}
